QUERIES = [
    "Account Manager",
    "Accountant",
    "Academic Coordinator",
    "Administrative Officer",
    "AI Researcher",
    "Animator",
    "Area Sales Manager",
    "Assistant Professor",
    "Audit Manager",
    "Back Office Executive",
    "Bank Clerk",
    "BPO Executive",
    "Branch Manager",
    "Brand Manager",
    "Business Analyst",
    "Business Development Manager",
    "CA (Chartered Accountant)",
    "Call Center Supervisor",
    "Campaign Manager",
    "Chief Executive Officer (CEO)",
    "Chief Operating Officer (COO)",
    "Civil Engineer",
    "Clerk",
    "Cloud Engineer",
    "Cloud Operations Manager",
    "Community Lead",
    "Compliance Officer",
    "Construction Site Coordinator",
    "Content Lead",
    "Content Writer",
    "Copywriter",
    "Crew Leader",
    "Cybersecurity Analyst",
    "Customer Service Team Lead",
    "Customer Support Executive",
    "Customer Success Manager",
    "Data Analyst",
    "Data Entry Operator",
    "Data Scientist",
    "Database Administrator",
    "Delivery Executive",
    "Design Lead",
    "DevOps Engineer",
    "DevOps Lead",
    "Digital Marketing Manager",
    "Digital Marketer",
    "Doctor",
    "Electrical Engineer",
    "Engineering Manager",
    "Executive Director",
    "Field Sales Officer",
    "Field Service Lead",
    "Finance Executive",
    "Finance Manager",
    "Financial Analyst",
    "Fleet Manager",
    "Floor Supervisor",
    "Full Stack Developer",
    "General Manager",
    "Graphic Designer",
    "HOD (Head of Department)",
    "HR Executive",
    "HR Manager",
    "Illustrator",
    "Infrastructure Manager",
    "Insurance Advisor",
    "Inventory Control Manager",
    "Inventory Specialist",
    "Inventory Supervisor",
    "Investment Banker",
    "IT Coordinator",
    "IT Manager",
    "IT Support Technician",
    "Journalist",
    "Junior Project Coordinator",
    "Lab In-Charge",
    "Lab Technician",
    "Lecturer",
    "Legal Advisor",
    "Legal Compliance Officer",
    "Loan Officer",
    "Logistics Executive",
    "Logistics Manager",
    "Machine Learning Engineer",
    "Machine Operator",
    "Maintenance In-Charge",
    "Managing Director",
    "Marketing Executive",
    "Marketing Manager",
    "Mechanical Engineer",
    "Medical Coder",
    "Mechanic",
    "Network Engineer",
    "Nurse",
    "Office Assistant",
    "Office Coordinator",
    "Online Tutor",
    "Operations Executive",
    "Operations Manager",
    "Pharmacist",
    "Plumber",
    "Product Manager"
    "Production Executive",
	"Project Coordinator",]